#!/usr/bin/env python3
"""Build reproducible native-skill and single-file chat distributions."""
import argparse
import io
import json
from pathlib import Path
import re
from zipfile import ZipFile, ZipInfo, ZIP_DEFLATED

ROOT = Path(__file__).resolve().parents[1]
PLUGIN = ROOT / 'plugins/anti-inflammatory-kitchen'
# Explicit allowlist: caches, personal state and accidental files never ship.
SKILL_FILES = (
    'SKILL.md', 'agents/openai.yaml', 'scripts/kitchen.py',
    'references/food-table.md', 'references/recipe-rules.md',
    'references/state-files.md', 'references/visuals.md', 'references/nutrition-plan.md',
)


def skill_files():
    files = []
    for name in SKILL_FILES:
        source = ROOT / 'kitchen' / name
        if source.is_symlink() or not source.is_file():
            raise ValueError(f'Missing or symlinked skill source: {source}')
        files.append((name, source))
    return files


def archive_bytes():
    return zip_bytes({'kitchen/' + name: source.read_bytes() for name, source in skill_files()})


def zip_bytes(files):
    data = io.BytesIO()
    with ZipFile(data, 'w', ZIP_DEFLATED) as archive:
        for name, content in sorted(files.items()):
            entry = ZipInfo(name, (2026, 1, 1, 0, 0, 0))
            entry.compress_type = ZIP_DEFLATED
            entry.create_system = 3
            entry.external_attr = 0o644 << 16
            archive.writestr(entry, content)
    return data.getvalue()


def package(destination=None):
    destination = Path(destination or ROOT / 'dist/kitchen.zip')
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_bytes(archive_bytes())
    return destination


def chat_guide():
    sections = [('SKILL.md', 'workflow'), ('references/food-table.md', 'food-table'),
                ('references/state-files.md', 'state-files'), ('references/nutrition-plan.md', 'nutrition-plan'),
                ('references/recipe-rules.md', 'recipe-rules'),
                ('references/visuals.md', 'visuals')]
    preface = '''# 抗炎厨房 / Anti-Inflammatory Kitchen · Chat guide

<!-- Generated by scripts/package_skill.py; edit kitchen/ sources, then rebuild. -->

把本文件上传到支持文件阅读的 AI 对话中，或复制全文，并明确要求助手按此指南工作。
Upload this file to an AI chat that can read attachments, or paste its complete contents, and ask the assistant to follow it.

这是对话导入指南，不是账号级 skill 安装。是否能读取附件、执行代码、输出视觉或跨聊天保存，取决于所用产品、版本与套餐。本文件不启用任何新权限。
This is a conversation guide, not an account-wide skill installation. Attachments, code execution, visual output and persistence depend on your host product and plan.

使用本单文件时：
- 下文各项参考材料已经内嵌，不需要访问本地 references/ 路径。
- 本指南未附 Python 脚本，不执行下文的本地命令，不声称跑过脚本；按食材表手算并注明。
- 无可用视觉工具时用 Markdown 表格。先完成用户的厨房任务，不要求安装开发工具。
- 无持久文件或记忆工具时，只在当前对话维护记录；提供可复制的状态快照，换对话时由用户带入。不得承诺自动同步或永久保存。
- 跟随用户语言回答；固定中文类别名可同时附上翻译，存储与计数仍使用同一套类别。

When using this single file: use the embedded references, calculate manually and say so (the Python helper is not included), use text tables when rendering is unavailable, and export a state snapshot when persistent storage is unavailable. Respond in the user's language; translated labels can accompany canonical Chinese categories.

开始使用 / Start:
> 请按附件中的抗炎厨房指南工作。先说明本次能否保存库存、执行脚本，然后等我报食材；现在不要生成菜谱。
> Follow the attached Kitchen guide. Tell me whether this session can save inventory or run scripts, then wait for my ingredients. Do not suggest recipes yet.

'''
    out = [preface]
    targets = {name: anchor for name, anchor in sections}
    for name, anchor in sections:
        content = (ROOT / 'kitchen' / name).read_text(encoding='utf-8')
        if name == 'SKILL.md':
            content = re.sub(r'\A---\n.*?\n---\n', '', content, count=1, flags=re.S)
        for target, link in targets.items():
            content = content.replace('](' + target + ')', '](#' + link + ')')
            if name.startswith('references/') and target.startswith('references/'):
                content = content.replace('](' + target.removeprefix('references/') + ')', '](#' + link + ')')
        out.extend([f'\n---\n\n<a id="{anchor}"></a>\n\n', content, '\n'])
    return ''.join(out).encode('utf-8')


def plugin_files():
    """One skill source, with small manifests for each supported plugin host."""
    manifest = json.loads((PLUGIN / '.codex-plugin/plugin.json').read_text(encoding='utf-8'))
    common = {key: manifest[key] for key in
              ('name', 'version', 'description', 'author', 'homepage', 'repository', 'license', 'keywords')}
    portable = {'$schema': 'https://agent-plugins.org/schemas/1.0.0/plugin.schema.json', **common,
                'extensions': {'com.openai': {'interface': manifest['interface']}}}
    as_json = lambda value: (json.dumps(value, ensure_ascii=False, indent=2) + '\n').encode('utf-8')
    files = {
        'plugin.json': as_json(portable),
        '.codex-plugin/plugin.json': as_json(manifest),
        '.claude-plugin/plugin.json': as_json(common),
        '.cursor-plugin/plugin.json': as_json(common),
        'README.md': (ROOT / 'docs/plugin-readme.md').read_bytes(),
        'gemini-extension.json': as_json({key: common[key] for key in ('name', 'version', 'description')}),
        'LICENSE': (ROOT / 'LICENSE').read_bytes(),
    }
    files.update({'skills/kitchen/' + name: source.read_bytes() for name, source in skill_files()})
    return files


def distributions():
    return {'kitchen.zip': archive_bytes(), 'kitchen-chat-guide.md': chat_guide(),
            'anti-inflammatory-kitchen-plugin.zip': zip_bytes(plugin_files())}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--publish', action='store_true', help='Rebuild committed downloads/')
    parser.add_argument('--check', action='store_true', help='Verify downloads/ matches current sources')
    args = parser.parse_args()
    if args.publish and args.check:
        parser.error('Choose --publish or --check')
    if args.check:
        stale = [name for name, content in distributions().items()
                 if not (ROOT / 'downloads' / name).is_file()
                 or (ROOT / 'downloads' / name).read_bytes() != content]
        if stale:
            parser.error('Stale downloads: ' + ', '.join(stale) + '; run python3 scripts/package_skill.py --publish')
        files = plugin_files()
        expected = set(files)
        actual = {path.relative_to(PLUGIN).as_posix() for path in PLUGIN.rglob('*') if path.is_file()
                  and '__pycache__' not in path.parts and path.name != '.DS_Store'}
        if actual != expected or any((PLUGIN / name).read_bytes() != content for name, content in files.items()):
            parser.error('Plugin tree differs from sources; rebuild with --publish and remove unexpected files')
        print('Download artifacts match skill sources.')
    else:
        if args.publish:
            for name, content in plugin_files().items():
                output = PLUGIN / name
                output.parent.mkdir(parents=True, exist_ok=True)
                output.write_bytes(content)
        directory = ROOT / ('downloads' if args.publish else 'dist')
        directory.mkdir(parents=True, exist_ok=True)
        for name, content in distributions().items():
            path = directory / name
            path.write_bytes(content)
            print(path)


if __name__ == '__main__':
    main()
